        <div id="page-wrapper">
<?php View::content() ?>
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Nuevo Usuario</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <?php echo Form::open() ?>
              <div class="form-group">
                <label for="exampleInputEmail1">Login</label>
                <?php echo Form::text("usuarios.login","class='form-control'") ?>
                
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Contraseña</label>
                <?php echo Form::pass("usuarios.password","class='form-control'") ?>
              </div>
            
              <button type="submit" class="btn btn-primary">Agregar</button>
            </form>
        </div>
        <!-- /#page-wrapper -->

    </div>
<script type="text/javascript">
    $(document).ready(function(){
        $("#usuarios_login").val("");
    })
</script>