<?php View::content() ?>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Nuevo Usuario</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <?php echo Form::open() ?>
              <div class="form-group">
                <label for="Login">Login</label>
                <?php echo Form::hidden("usuarios.id") ?>
                <?php echo Form::text("usuarios.login","class='form-control'") ?>
                
              </div>
              <div class="form-group">
                <label for="Contraseña">Contraseña</label>
                <?php echo Form::pass("usuarios.password","class='form-control' placeholder='Nueva Contraseña...'",'') ?>
              </div>
              <div class="form-group">
                <label for="Role">Role</label>
                <?php echo Form::dbselect("usuarios.roles_id",null,null,"Seleccione","class='form-control'") ?>
              </div>            
             
              <button type="submit" class="btn btn-primary">Actualizar</button>
              <?php echo Html::link("usuarios/delete/{$usuarios->id}","Eliminar","class='btn btn-danger'") ?>

            </form>
        </div>
        <!-- /#page-wrapper -->

    </div>