<?php View::content() ?>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Ver Usuario</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
           <div class="btn-group" role="group" aria-label="...">
              <?php echo Html::link("contactos/create/{$usuario->id}","Agregar Un Contacto","class='btn btn-primary'") ?>
              <?php echo Html::link("contactos/usuario/{$usuario->id}","Ver Contactos de Usuario","class='btn btn-primary'") ?>
            </div>
            <h3>Mails Enviados</h3>
            <table class="table">
                <thead>
                    <td>Mail</td>
                    <td>Destinatario</td>
                </thead>
                <tbody>
                    <tr>
                        <td>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit totam voluptatum, labore facere, porro quia hic temporibus doloribus eum autem assumenda minima fugiat dolore! Sit fugiat expedita eligendi at quisquam!</td>
                        <td>aasd@asd.com</td>
                    </tr>
                    <tr>
                        <td>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit totam voluptatum, labore facere, porro quia hic temporibus doloribus eum autem assumenda minima fugiat dolore! Sit fugiat expedita eligendi at quisquam!</td>
                        <td>aasd@asd.com</td>
                    </tr>
                    <tr>
                        <td>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit totam voluptatum, labore facere, porro quia hic temporibus doloribus eum autem assumenda minima fugiat dolore! Sit fugiat expedita eligendi at quisquam!</td>
                        <td>aasd@asd.com</td>
                    </tr>
                    <tr>
                        <td>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit totam voluptatum, labore facere, porro quia hic temporibus doloribus eum autem assumenda minima fugiat dolore! Sit fugiat expedita eligendi at quisquam!</td>
                        <td>aasd@asd.com</td>
                    </tr>
                    <tr>
                        <td>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit totam voluptatum, labore facere, porro quia hic temporibus doloribus eum autem assumenda minima fugiat dolore! Sit fugiat expedita eligendi at quisquam!</td>
                        <td>aasd@asd.com</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <!-- /#page-wrapper -->

    </div>
