        <div id="page-wrapper">
<?php View::content() ?>
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Crear Contacto</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <?php echo Form::open() ?>
              <div class="form-group">
                <label for="Nombre">Nombre</label>
                <?php echo Form::text("contactos.nombre","class='form-control' placeholder='Nombre Completo...'") ?>
                
              </div>
              <div class="form-group">
                <label for="Descripción">Descripción</label>
                <?php echo Form::textarea("contactos.descripcion","class='form-control' placeholder='Descripción...'") ?>
              </div>
              <div class="form-group">
                <label for="Email">Email</label>
                <?php echo Form::email("contactos.email","class='form-control' placeholder='Email...'") ?>
              </div>            
              <button type="submit" class="btn btn-primary">Agregar</button>
              <?php echo Html::link("usuarios/ver/{$usuario->id}","Volver a Usuario","class='btn btn-primary'") ?>
            </form>
        </div>
        <!-- /#page-wrapper -->

    </div>
