        <div id="page-wrapper">
          <?php View::content() ?>
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Editar Contacto</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="btn-group" role="group" aria-label="...">
              <?php echo Html::link("#","< Volver","class='btn btn-primary' Onclick='history.back(1)'") ?>
            </div>
            <br>
            <br>
            <?php echo Form::open() ?>
              <div class="form-group">
                <label for="Nombre">Nombre</label>
                <?php echo Form::hidden("contactos.id") ?>
                <?php echo Form::text("contactos.nombre","class='form-control' placeholder='Nombre Completo...'") ?>
                
              </div>
              <div class="form-group">
                <label for="Descripción">Descripción</label>
                <?php echo Form::textarea("contactos.descripcion","class='form-control' placeholder='Descripción...'") ?>
              </div>
              <div class="form-group">
                <label for="Email">Email</label>
                <?php echo Form::email("contactos.email","class='form-control' placeholder='Email...'") ?>
              </div>            
              <button type="submit" class="btn btn-primary">Actualizar</button>
              <?php echo Html::link("contactos/delete/$contactos->id/$usuario->id","Eliminar","class='btn btn-danger'") ?>
            </form>         
        </div>
        <!-- /#page-wrapper -->

    </div>
