        <div id="page-wrapper">
<?php View::content() ?>
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Contactos de Usuario <?php echo $usuario->login ?></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <table class="table">
              <thead>
                <td>Nombre</td>
                <td>Descripción</td>
                <td>Email</td>
                <td>Creado</td>
                <td>Acción</td>
              </thead>
              <?php foreach ($contactos as $key => $value): ?>
                <tr>
                  <td><?php echo $value->nombre ?></td>
                  <td><?php echo $value->descripcion ?></td>
                  <td><?php echo $value->email ?></td>
                  <td><?php echo $value->created ?></td>
                  <td></td>
                </tr>
              <?php endforeach ?>
            </table>
        </div>
        <!-- /#page-wrapper -->

    </div>
