<?php View::content() ?>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Editar Role</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <?php echo Form::open() ?>
              <div class="form-group">
                <label for="exampleInputEmail1">Role</label>
                <?php echo Form::hidden("roles.id") ?>
                <?php echo Form::text("roles.role","class='form-control'") ?>
                
              </div>
             
              <button type="submit" class="btn btn-primary">Actualizar</button>
              <?php echo Html::link("roles/delete/{$roles->id}","Eliminar","class='btn btn-danger'") ?>
            </form>
        </div>
        <!-- /#page-wrapper -->

    </div>