<!DOCTYPE html>
<html lang="es">
  <head>
    <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title><?php echo $kumbia_title ?></title>
    <!-- Bootstrap Core CSS -->
    <link href="<?php echo PUBLIC_PATH ?>/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="<?php echo PUBLIC_PATH ?>/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="<?php echo PUBLIC_PATH ?>/dist/css/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?php echo PUBLIC_PATH ?>/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="<?php echo PUBLIC_PATH ?>/bower_components/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="<?php echo PUBLIC_PATH ?>/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <?php echo Html::includeCss() ?>

    <script src="<?php echo PUBLIC_PATH ?>/bower_components/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo PUBLIC_PATH ?>/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="<?php echo PUBLIC_PATH ?>/bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->

    <!-- Custom Theme JavaScript -->
    <script src="<?php echo PUBLIC_PATH ?>/dist/js/sb-admin-2.js"></script>

  </head>
  <body>
      <div id="wrapper">
        <?php View::partial("top_navbar",null,array("kumbia_title"=>$kumbia_title)) ?>
        
        <?php View::content() ?>

      </div>
      
    <script src="<?php echo PUBLIC_PATH ?>/bower_components/raphael/raphael-min.js"></script>
    <script src="<?php echo PUBLIC_PATH ?>/bower_components/morrisjs/morris.min.js"></script>
    <script src="<?php echo PUBLIC_PATH ?>/javascript/morris-data.js"></script>
  </body>
</html>
